#!/usr/bin/env node
/**
 * cobra-effect generator
 *
 * Usage:
 *   node generate.js <input-dir> <source-html> [output-dir]
 *   node generate.js <input-dir> <source-html> --nextjs <nextjs-root>
 *   node generate.js <input-dir> <source-html> --validate
 *   node generate.js <input-dir> <source-html> --dry-run
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const REQUIRED_NODES = ['A', 'B', 'C', 'D'];
const REQUIRED_STATES = [
  'high_metric_depleted',
  'high_metric_intact',
  'low_metric_depleted',
  'low_metric_intact'
];

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ─────────────────────────────────────────────────────────────────────────────
// VALIDATION
// ─────────────────────────────────────────────────────────────────────────────

function validate(config) {
  const errors = [], warnings = [];

  if (!config.meta)           errors.push('Missing "meta" object');
  else {
    if (!config.meta.title)       errors.push('meta.title is required');
    if (!config.meta.description) warnings.push('meta.description missing — card will have no subtitle');
    if (!config.meta.keywords)    warnings.push('meta.keywords missing — tag filter will not work');
    if (!config.meta.slug)        warnings.push('meta.slug not set — will derive from title');
  }

  if (!config.scenario) errors.push('Missing "scenario" — the framing context for the game');
  if (!config.role)     errors.push('Missing "role" — who the player is');
  if (!config.context)  errors.push('Missing "context" — what situation the player is in');

  if (typeof config.board_target !== 'number') errors.push('board_target must be a number');
  if (typeof config.tokens_per_turn !== 'number') errors.push('tokens_per_turn must be a number');
  if (typeof config.turns !== 'number') errors.push('turns must be a number');

  // Nodes
  if (!config.nodes) {
    errors.push('Missing "nodes" object');
  } else {
    REQUIRED_NODES.forEach(k => {
      if (!config.nodes[k]) {
        errors.push('Missing node "' + k + '"');
      } else {
        const n = config.nodes[k];
        if (!n.label)         errors.push('nodes.' + k + '.label is required');
        if (!n.description)   warnings.push('nodes.' + k + '.description missing');
        if (typeof n.starting_value !== 'number') errors.push('nodes.' + k + '.starting_value must be a number');
        else if (n.starting_value < 0 || n.starting_value > 100) errors.push('nodes.' + k + '.starting_value must be 0-100');
      }
    });
    if (config.nodes.D && !config.nodes.D.is_metric) {
      warnings.push('nodes.D.is_metric is not set — D is the target metric, set is_metric: true');
    }
  }

  // _mechanic_argument warning
  if (config._mechanic_argument) {
    warnings.push('_mechanic_argument is engine-fixed and will be stripped from user-config.js');
  }

  // Hidden feedback
  if (!config.hidden_feedback) {
    errors.push('Missing "hidden_feedback" — defines the causal thresholds');
  } else {
    if (typeof config.hidden_feedback.A_to_C_threshold !== 'number')
      errors.push('hidden_feedback.A_to_C_threshold must be a number');
    if (typeof config.hidden_feedback.D_acceleration_threshold !== 'number')
      errors.push('hidden_feedback.D_acceleration_threshold must be a number');
  }

  // Reveal
  if (!config.reveal) {
    errors.push('Missing "reveal" object');
  } else {
    if (!config.reveal.closing_question) errors.push('reveal.closing_question is required');
    if (!config.reveal.states) {
      errors.push('Missing reveal.states');
    } else {
      REQUIRED_STATES.forEach(s => {
        if (!config.reveal.states[s]) {
          errors.push('Missing reveal.states.' + s);
        } else if (!config.reveal.states[s].what_the_player_did) {
          errors.push('reveal.states.' + s + '.what_the_player_did is required');
        }
      });
    }
  }

  return { errors, warnings };
}

// ─────────────────────────────────────────────────────────────────────────────
// USER-CONFIG GENERATION
// ─────────────────────────────────────────────────────────────────────────────

function generateUserConfig(config) {
  const clean = JSON.parse(JSON.stringify(config));
  delete clean._mechanic_argument;
  if (clean.hidden_feedback) delete clean.hidden_feedback._note;
  delete clean.meta;

  return '// user-config.js — GENERATED FILE\n' +
    '// Edit game.json and re-run generate.js\n' +
    '// Do not edit this file directly.\n' +
    '//\n' +
    '// NOTE: _mechanic_argument is engine-fixed and not configurable.\n' +
    '// The ethical argument this template makes belongs to the engine,\n' +
    '// not the student\'s scenario.\n\n' +
    'GAME_CONFIG = ' + JSON.stringify(clean, null, 2) + ';\n';
}

// ─────────────────────────────────────────────────────────────────────────────
// INDEX.HTML PATCHING
// ─────────────────────────────────────────────────────────────────────────────

function patchIndexHtml(src, config) {
  let html = src;
  const meta = config.meta;

  html = html.replace(/<title>[^<]*<\/title>/, '<title>' + escapeHtml(meta.title) + '</title>');

  const descTag = '<meta name="description" content="' + escapeHtml(meta.description || '') + '"/>';
  if (/<meta[^>]+name="description"/.test(html)) {
    html = html.replace(/<meta[^>]+name="description"[^>]*>/, descTag);
  } else {
    html = html.replace('</head>', '  ' + descTag + '\n</head>');
  }

  const kwString = (meta.keywords || []).join(', ');
  const kwTag = '<meta name="keywords" content="' + escapeHtml(kwString) + '"/>';
  if (/<meta[^>]+name="keywords"/.test(html)) {
    html = html.replace(/<meta[^>]+name="keywords"[^>]*>/, kwTag);
  } else {
    html = html.replace('</head>', '  ' + kwTag + '\n</head>');
  }

  return html;
}

// ─────────────────────────────────────────────────────────────────────────────
// PLACEHOLDER PNG GENERATION
// ─────────────────────────────────────────────────────────────────────────────

function generatePlaceholders(config, assetsDir, inputDir, dryRun) {
  let canvas;
  try {
    canvas = require('canvas');
  } catch (e) {
    console.log('  WARN: canvas package not found — placeholder images not generated');
    console.log('        Install with: npm install canvas');
    return;
  }

  const { createCanvas } = canvas;
  const W = 120, H = 120;

  REQUIRED_NODES.forEach(k => {
    const n = config.nodes[k];
    if (!n) return;

    const imgPath = path.join(inputDir, 'assets', k.toLowerCase() + '.png');
    if (fs.existsSync(imgPath)) {
      console.log('  assets: using existing ' + k.toLowerCase() + '.png');
      return;
    }

    if (dryRun) {
      console.log('  [dry-run] Would generate: assets/' + k.toLowerCase() + '.png (' + W + 'x' + H + 'px)');
      return;
    }

    const c = createCanvas(W, H);
    const ctx = c.getContext('2d');
    const isMetric = k === 'D';

    ctx.fillStyle = isMetric ? '#FAEEDA' : '#E8E0D0';
    ctx.fillRect(0, 0, W, H);
    ctx.strokeStyle = isMetric ? '#854F0B' : '#9C9680';
    ctx.lineWidth = 2;
    ctx.strokeRect(1, 1, W - 2, H - 2);

    ctx.fillStyle = isMetric ? '#854F0B' : '#4A4A4A';
    ctx.font = 'bold 32px Arial, sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(k, W / 2, H / 2 - 10);

    ctx.fillStyle = isMetric ? '#854F0B' : '#6B6B5E';
    ctx.font = '12px Arial, sans-serif';
    const firstWord = (n.label || k).split(/[\s,]/)[0];
    ctx.fillText(firstWord, W / 2, H / 2 + 20);

    fs.writeFileSync(path.join(assetsDir, k.toLowerCase() + '.png'), c.toBuffer('image/png'));
    console.log('  assets: generated ' + k.toLowerCase() + '.png');
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h') || args.length < 2) {
    console.log('\ncobra-effect generator');
    console.log('Usage:');
    console.log('  node generate.js <input-dir> <source-html> [output-dir]');
    console.log('  node generate.js <input-dir> <source-html> --nextjs <nextjs-root>');
    console.log('  node generate.js <input-dir> <source-html> --validate');
    console.log('  node generate.js <input-dir> <source-html> --dry-run\n');
    process.exit(args.length < 2 ? 1 : 0);
  }

  const inputDir    = path.resolve(args[0]);
  const sourceHtml  = path.resolve(args[1]);
  const validateOnly = args.includes('--validate');
  const dryRun      = args.includes('--dry-run');

  console.log('=== cobra-effect generator ===\n');

  // Read game.json
  let configPath = path.join(inputDir, 'game.json');
  if (!fs.existsSync(configPath)) {
    configPath = path.join(inputDir, 'example-game.json');
  }
  if (!fs.existsSync(configPath)) {
    console.error('ERROR: game.json not found in: ' + inputDir);
    process.exit(1);
  }

  let config;
  try {
    config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  } catch (e) {
    console.error('ERROR: Invalid JSON in game.json: ' + e.message);
    process.exit(1);
  }

  if (!config.meta) config.meta = {};
  if (!config.meta.slug) config.meta.slug = slugify(config.meta.title || config.scenario || 'cobra-effect');

  // Normalize keywords
  if (config.meta.keywords && typeof config.meta.keywords === 'string') {
    config.meta.keywords = config.meta.keywords.split(',').map(k => k.trim()).filter(Boolean);
  }

  // Validate
  const { errors, warnings } = validate(config);
  if (warnings.length) {
    console.log('Warnings:');
    warnings.forEach(w => console.log('  WARN: ' + w));
    console.log('');
  }
  if (errors.length) {
    console.error('Validation errors:');
    errors.forEach(e => console.error('  ERROR: ' + e));
    console.error('\n' + errors.length + ' errors, ' + warnings.length + ' warnings');
    process.exit(1);
  }
  console.log('Validation passed. 0 errors, ' + warnings.length + ' warnings\n');
  if (validateOnly) process.exit(0);

  // Source HTML
  if (!fs.existsSync(sourceHtml)) {
    console.error('ERROR: Source HTML not found: ' + sourceHtml);
    process.exit(1);
  }

  // Output directory
  let outputDir;
  const nextjsIdx = args.indexOf('--nextjs');
  if (nextjsIdx !== -1) {
    const nextjsRoot = args[nextjsIdx + 1];
    if (!nextjsRoot || nextjsRoot.startsWith('--')) {
      console.error('ERROR: --nextjs requires a path argument');
      process.exit(1);
    }
    outputDir = path.join(path.resolve(nextjsRoot), 'public', 'games', config.meta.slug);
  } else if (!dryRun) {
    outputDir = path.resolve(
      args.find((a, i) => !a.startsWith('-') && i > 1) || 'dist'
    );
  }

  if (dryRun) {
    console.log('[dry-run] Files that would be generated:');
    console.log('  index.html (patched: title="' + config.meta.title + '", description, keywords)');
    console.log('  user-config.js (GAME_CONFIG from game.json, _mechanic_argument stripped)');
    generatePlaceholders(config, 'assets', inputDir, true);
    console.log('\nDry run complete. No files written.');
    process.exit(0);
  }

  console.log('Config     : ' + configPath);
  console.log('Source HTML: ' + sourceHtml);
  console.log('Slug       : ' + config.meta.slug);
  console.log('Output     : ' + outputDir);
  console.log('');

  // Build
  fs.mkdirSync(outputDir, { recursive: true });
  fs.mkdirSync(path.join(outputDir, 'assets'), { recursive: true });

  // Patch and write index.html
  const srcHtml = fs.readFileSync(sourceHtml, 'utf8');
  fs.writeFileSync(path.join(outputDir, 'index.html'), patchIndexHtml(srcHtml, config));
  console.log('Wrote ' + path.join(outputDir, 'index.html'));

  // Generate user-config.js
  fs.writeFileSync(path.join(outputDir, 'user-config.js'), generateUserConfig(config));
  console.log('Wrote ' + path.join(outputDir, 'user-config.js'));

  // Copy user assets
  const userAssetsDir = path.join(inputDir, 'assets');
  if (fs.existsSync(userAssetsDir)) {
    const files = fs.readdirSync(userAssetsDir).filter(f => !f.startsWith('.'));
    files.forEach(f => {
      fs.copyFileSync(path.join(userAssetsDir, f), path.join(outputDir, 'assets', f));
    });
    if (files.length > 0) console.log('Copied ' + files.length + ' user assets');
  }

  // Generate placeholder PNGs
  generatePlaceholders(config, path.join(outputDir, 'assets'), inputDir, false);

  console.log('\n=== Generation complete ===');
  console.log('Deploy: push to main, appears at /games/' + config.meta.slug);
}

main();
