#!/usr/bin/env node
/**
 * the-rule generator
 *
 * Usage:
 *   node generate.js <input-dir> <source-html> [output-dir]
 *   node generate.js <input-dir> <source-html> --nextjs <nextjs-root>
 *   node generate.js <input-dir> <source-html> --validate
 *   node generate.js <input-dir> <source-html> --dry-run
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const REQUIRED_STATES = ['none_accepted', 'first_only', 'escalating', 'all_accepted'];

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ── VALIDATION ───────────────────────────────────────────────────────────────

function validate(config) {
  const errors = [], warnings = [];

  if (!config.meta) errors.push('Missing "meta" object');
  else {
    if (!config.meta.title)       errors.push('meta.title is required');
    if (!config.meta.description) warnings.push('meta.description missing');
    if (!config.meta.keywords)    warnings.push('meta.keywords missing');
    if (!config.meta.slug)        warnings.push('meta.slug not set — will derive from title');
  }

  if (!config.official_role) errors.push('Missing "official_role"');
  if (!config.context)       errors.push('Missing "context"');
  if (!config.the_rule)      errors.push('Missing "the_rule"');
  if (!config.the_stakes)    warnings.push('Missing "the_stakes"');
  if (!config.fixed_punishment) errors.push('Missing "fixed_punishment"');

  if (!Array.isArray(config.inducements) || config.inducements.length < 2) {
    errors.push('inducements must be an array with at least 2 entries');
  } else if (config.inducements.length > 5) {
    warnings.push('More than 5 inducements — consider whether the escalation arc remains clear');
  } else {
    config.inducements.forEach(function(ind, i) {
      if (!ind.offer)    errors.push('inducements[' + i + '].offer is required');
      if (!ind.offeror)  warnings.push('inducements[' + i + '].offeror missing');
      if (!ind.context)  warnings.push('inducements[' + i + '].context missing');
      if (!ind.cost_label) warnings.push('inducements[' + i + '].cost_label missing');
    });
    var offers = config.inducements.map(function(i) { return i.offer; });
    if (new Set(offers).size < offers.length) {
      warnings.push('Some inducements have identical offer text — escalation requires distinct offers');
    }
  }

  if (!config.reveal) {
    errors.push('Missing "reveal" object');
  } else {
    if (!config.reveal.closing_question) errors.push('reveal.closing_question is required');
    if (!config.reveal.states) {
      errors.push('Missing reveal.states');
    } else {
      REQUIRED_STATES.forEach(function(s) {
        if (!config.reveal.states[s]) {
          errors.push('Missing reveal.states.' + s);
        } else if (!config.reveal.states[s].what_the_player_did) {
          errors.push('reveal.states.' + s + '.what_the_player_did is required');
        } else {
          var text = config.reveal.states[s].what_the_player_did;
          if (/\$[\d,]+/.test(text)) {
            warnings.push('reveal.states.' + s + ': state text contains a dollar amount. ' +
              'Describe the pattern, not the sum.');
          }
        }
      });
    }
  }

  if (config._mechanic_argument) {
    warnings.push('_mechanic_argument is engine-fixed and will be stripped from user-config.js');
  }

  return { errors, warnings };
}

// ── USER-CONFIG GENERATION ───────────────────────────────────────────────────

function generateUserConfig(config) {
  var clean = JSON.parse(JSON.stringify(config));
  delete clean._mechanic_argument;
  delete clean.meta;

  return '// user-config.js — GENERATED FILE\n' +
    '// Edit game.json and re-run generate.js\n' +
    '// Do not edit this file directly.\n' +
    '//\n' +
    '// NOTE: _mechanic_argument is engine-fixed and not configurable.\n' +
    '// The ethical argument this template makes belongs to the engine.\n\n' +
    'GAME_CONFIG = ' + JSON.stringify(clean, null, 2) + ';\n';
}

// ── HTML PATCHING ────────────────────────────────────────────────────────────

function patchHtml(src, config) {
  var html = src;
  var meta = config.meta;

  html = html.replace(/<title>[^<]*<\/title>/, '<title>' + escapeHtml(meta.title) + '</title>');

  var descTag = '<meta name="description" content="' + escapeHtml(meta.description || '') + '"/>';
  if (/<meta[^>]+name="description"/.test(html)) {
    html = html.replace(/<meta[^>]+name="description"[^>]*>/, descTag);
  } else {
    html = html.replace('</head>', '  ' + descTag + '\n</head>');
  }

  var kwString = (meta.keywords || []).join(', ');
  var kwTag = '<meta name="keywords" content="' + escapeHtml(kwString) + '"/>';
  if (/<meta[^>]+name="keywords"/.test(html)) {
    html = html.replace(/<meta[^>]+name="keywords"[^>]*>/, kwTag);
  } else {
    html = html.replace('</head>', '  ' + kwTag + '\n</head>');
  }

  return html;
}

// ── MAIN ─────────────────────────────────────────────────────────────────────

function main() {
  var args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h') || args.length < 2) {
    console.log('\nthe-rule generator');
    console.log('Usage:');
    console.log('  node generate.js <input-dir> <source-html> [output-dir]');
    console.log('  node generate.js <input-dir> <source-html> --nextjs <nextjs-root>');
    console.log('  node generate.js <input-dir> <source-html> --validate');
    console.log('  node generate.js <input-dir> <source-html> --dry-run\n');
    process.exit(args.length < 2 ? 1 : 0);
  }

  var inputDir    = path.resolve(args[0]);
  var sourceHtml  = path.resolve(args[1]);
  var validateOnly = args.includes('--validate');
  var dryRun       = args.includes('--dry-run');

  console.log('=== the-rule generator ===\n');

  var configPath = path.join(inputDir, 'game.json');
  if (!fs.existsSync(configPath)) {
    console.error('ERROR: game.json not found in: ' + inputDir);
    process.exit(1);
  }

  var config;
  try {
    config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  } catch (e) {
    console.error('ERROR: Invalid JSON: ' + e.message);
    process.exit(1);
  }

  if (!config.meta) config.meta = {};
  if (!config.meta.slug) config.meta.slug = slugify(config.meta.title || 'the-rule');
  if (config.meta.keywords && typeof config.meta.keywords === 'string') {
    config.meta.keywords = config.meta.keywords.split(',').map(function(k) { return k.trim(); }).filter(Boolean);
  }

  var result = validate(config);
  if (result.warnings.length) {
    console.log('Warnings:');
    result.warnings.forEach(function(w) { console.log('  WARN: ' + w); });
    console.log('');
  }
  if (result.errors.length) {
    console.error('Validation errors:');
    result.errors.forEach(function(e) { console.error('  ERROR: ' + e); });
    console.error('\n' + result.errors.length + ' errors, ' + result.warnings.length + ' warnings');
    process.exit(1);
  }
  console.log('Validation passed. 0 errors, ' + result.warnings.length + ' warnings\n');
  if (validateOnly) process.exit(0);

  if (!fs.existsSync(sourceHtml)) {
    console.error('ERROR: Source HTML not found: ' + sourceHtml);
    process.exit(1);
  }

  var outputDir;
  var nextjsIdx = args.indexOf('--nextjs');
  if (nextjsIdx !== -1) {
    var nextjsRoot = args[nextjsIdx + 1];
    if (!nextjsRoot || nextjsRoot.startsWith('--')) {
      console.error('ERROR: --nextjs requires a path argument');
      process.exit(1);
    }
    outputDir = path.join(path.resolve(nextjsRoot), 'public', 'games', config.meta.slug);
  } else if (!dryRun) {
    outputDir = path.resolve(args.find(function(a, i) { return !a.startsWith('-') && i > 1; }) || 'dist');
  }

  if (dryRun) {
    console.log('[dry-run] Would write:');
    console.log('  index.html (patched: title="' + config.meta.title + '")');
    console.log('  user-config.js (GAME_CONFIG, _mechanic_argument stripped)');
    console.log('\nDry run complete.');
    process.exit(0);
  }

  console.log('Config     : ' + configPath);
  console.log('Source HTML: ' + sourceHtml);
  console.log('Slug       : ' + config.meta.slug);
  console.log('Output     : ' + outputDir + '\n');

  fs.mkdirSync(outputDir, { recursive: true });
  fs.mkdirSync(path.join(outputDir, 'assets'), { recursive: true });

  var srcHtml = fs.readFileSync(sourceHtml, 'utf8');
  fs.writeFileSync(path.join(outputDir, 'index.html'), patchHtml(srcHtml, config));
  console.log('Wrote ' + path.join(outputDir, 'index.html'));

  fs.writeFileSync(path.join(outputDir, 'user-config.js'), generateUserConfig(config));
  console.log('Wrote ' + path.join(outputDir, 'user-config.js'));

  var userAssetsDir = path.join(inputDir, 'assets');
  if (fs.existsSync(userAssetsDir)) {
    var files = fs.readdirSync(userAssetsDir).filter(function(f) { return !f.startsWith('.'); });
    files.forEach(function(f) {
      fs.copyFileSync(path.join(userAssetsDir, f), path.join(outputDir, 'assets', f));
    });
    if (files.length > 0) console.log('Copied ' + files.length + ' user assets');
  }

  console.log('\n=== Generation complete ===');
  console.log('Deploy: push to main, appears at /games/' + config.meta.slug);
}

main();
